/*
 * SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
 * SPDX-FileCopyrightText: 2023-2025 Konstantin Herud
 *
 * SPDX-License-Identifier: MIT
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ladenthin_llama_LlamaModel */

#ifndef _Included_net_ladenthin_llama_LlamaModel
#define _Included_net_ladenthin_llama_LlamaModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    embed
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_net_ladenthin_llama_LlamaModel_embed(JNIEnv *, jobject, jstring);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    encode
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_net_ladenthin_llama_LlamaModel_encode(JNIEnv *, jobject, jstring);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    setLogger
 * Signature: (Lnet/ladenthin/llama/args/LogFormat;Ljava/util/function/BiConsumer;)V
 */
JNIEXPORT void JNICALL Java_net_ladenthin_llama_LlamaModel_setLogger(JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    requestCompletion
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_ladenthin_llama_LlamaModel_requestCompletion(JNIEnv *, jobject, jstring);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    receiveCompletionJson
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_receiveCompletionJson(JNIEnv *, jobject, jint);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    cancelCompletion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_ladenthin_llama_LlamaModel_cancelCompletion(JNIEnv *, jobject, jint);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    decodeBytes
 * Signature: ([I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_ladenthin_llama_LlamaModel_decodeBytes(JNIEnv *, jobject, jintArray);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    loadModel
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_ladenthin_llama_LlamaModel_loadModel(JNIEnv *, jobject, jobjectArray);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    loadModelWithProgress
 * Signature: ([Ljava/lang/String;Lnet/ladenthin/llama/LoadProgressCallback;)V
 */
JNIEXPORT void JNICALL Java_net_ladenthin_llama_LlamaModel_loadModelWithProgress(JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ladenthin_llama_LlamaModel_delete(JNIEnv *, jobject);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    releaseTask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_ladenthin_llama_LlamaModel_releaseTask(JNIEnv *, jobject, jint);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    jsonSchemaToGrammarBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_ladenthin_llama_LlamaModel_jsonSchemaToGrammarBytes(JNIEnv *, jclass, jstring);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    nativeLlamaCppBuildInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_nativeLlamaCppBuildInfo(JNIEnv *, jclass);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    handleRerank
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleRerank(JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    applyTemplate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_applyTemplate(JNIEnv *, jobject, jstring);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    handleChatCompletions
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleChatCompletions(JNIEnv *, jobject, jstring);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    requestChatCompletion
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_ladenthin_llama_LlamaModel_requestChatCompletion(JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_net_ladenthin_llama_LlamaModel_requestChatCompletionStream(JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_receiveChatCompletionChunk(JNIEnv *, jobject, jint);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleCompletions(JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleCompletionsOai(JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleInfill(JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleEmbeddings(JNIEnv *, jobject, jstring, jboolean);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleTokenize(JNIEnv *, jobject, jstring, jboolean, jboolean);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleDetokenize(JNIEnv *, jobject, jintArray);

JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_handleSlotAction(JNIEnv *, jobject, jint, jint, jstring);

JNIEXPORT jboolean JNICALL Java_net_ladenthin_llama_LlamaModel_configureParallelInference(JNIEnv *, jobject, jstring);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    getModelMetaJson
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_getModelMetaJson(JNIEnv *, jobject);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    getLoraAdaptersJson
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_getLoraAdaptersJson(JNIEnv *, jobject);

/*
 * Class:     net_ladenthin_llama_LlamaModel
 * Method:    setLoraAdaptersJson
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ladenthin_llama_LlamaModel_setLoraAdaptersJson(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
