// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
// SPDX-FileCopyrightText: 2023-2025 Konstantin Heurer
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a test class as generated by Claude AI.
 *
 * <p>Applying this annotation documents the intent of the test class and allows tooling
 * to identify AI-generated tests for review or regeneration purposes.
 *
 * <p>Example:
 * <pre>
 * {@literal @}ClaudeGenerated(
 *     purpose = "Verify that Foo.bar() handles null inputs without throwing."
 * )
 * public class FooTest { ... }
 * </pre>
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)
public @interface ClaudeGenerated {

    /**
     * Describes what aspect of the production code this test class validates
     * and why those behaviours are important to cover.
     */
    String purpose();

    /**
     * The Claude model that generated the test class.
     * Defaults to the model active at the time of the last known generation run.
     */
    String model() default "claude-sonnet-4-6";
}
