// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.server;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

/**
 * Immutable, parsed configuration for {@link LlamaServer}, produced by
 * {@link LlamaServerArgs#parse(String[])}.
 *
 * <p>{@code ctxSize} and {@code threads} use {@code 0} as a sentinel meaning "leave the llama.cpp
 * default" — they are only applied to {@link net.ladenthin.llama.parameters.ModelParameters} when
 * positive. {@code gpuLayers} is always applied (its own default of {@code 0} already means
 * CPU-only).</p>
 *
 * <p>Value equality / {@code toString} are generated by Lombok over all fields.</p>
 */
@Getter
@ToString
@EqualsAndHashCode
public final class LlamaServerConfig {

    private final String host;
    private final int port;
    private final String modelPath;
    private final String modelAlias;
    private final int ctxSize;
    private final int gpuLayers;
    private final int threads;
    private final boolean embedding;

    /**
     * Create a server configuration.
     *
     * @param host       the interface to bind (e.g. {@code "127.0.0.1"} or {@code "0.0.0.0"})
     * @param port       the TCP port to listen on
     * @param modelPath  the path to the GGUF model file to load
     * @param modelAlias the identifier reported by {@code /v1/models}
     * @param ctxSize    context window size, or {@code 0} to use the llama.cpp default
     * @param gpuLayers  number of layers to offload to the GPU ({@code 0} = CPU-only)
     * @param threads    inference thread count, or {@code 0} to use the llama.cpp default
     * @param embedding  whether to load the model in embedding mode (enables {@code /v1/embeddings})
     */
    public LlamaServerConfig(
            String host,
            int port,
            String modelPath,
            String modelAlias,
            int ctxSize,
            int gpuLayers,
            int threads,
            boolean embedding) {
        this.host = host;
        this.port = port;
        this.modelPath = modelPath;
        this.modelAlias = modelAlias;
        this.ctxSize = ctxSize;
        this.gpuLayers = gpuLayers;
        this.threads = threads;
        this.embedding = embedding;
    }
}
