// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.server;

import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Immutable result of routing one HTTP request: an HTTP status code and a JSON body.
 *
 * <p>Produced by {@link OaiRouter#route(String, String, String)} and adapted to a NanoHTTPD
 * response by {@link OaiHttpServer}. Keeping it independent of NanoHTTPD lets the routing logic be
 * unit-tested without binding a socket. The body is always JSON (the server always replies with
 * {@code application/json}).</p>
 *
 * <p>Value equality / {@code toString} are generated by Lombok over the status and body.</p>
 */
@ToString
@EqualsAndHashCode
public final class OaiResponse {

    private final int status;
    private final String body;

    /**
     * Create a routed response.
     *
     * @param status the HTTP status code (e.g. {@code 200}, {@code 400}, {@code 404}, {@code 500})
     * @param body   the JSON response body
     */
    public OaiResponse(int status, String body) {
        this.status = status;
        this.body = body;
    }

    /**
     * The HTTP status code.
     *
     * @return the status code
     */
    public int getStatus() {
        return status;
    }

    /**
     * The JSON response body.
     *
     * @return the body
     */
    public String getBody() {
        return body;
    }
}
