// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.value;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.jspecify.annotations.Nullable;

/**
 * Per-completion timing data parsed from a llama.cpp result {@code timings} block.
 * <p>
 * The native {@code result_timings::to_json()} emits these fields:
 * {@code cache_n}, {@code prompt_n}, {@code prompt_ms}, {@code prompt_per_token_ms},
 * {@code prompt_per_second}, {@code predicted_n}, {@code predicted_ms},
 * {@code predicted_per_token_ms}, {@code predicted_per_second}. Speculative-decoding
 * runs additionally include {@code draft_n} and {@code draft_n_accepted}.
 * </p>
 */
@ToString
@EqualsAndHashCode
public final class Timings {

    private final int cacheN;
    private final long promptN;
    private final double promptMs;
    private final double promptPerSecond;
    private final long predictedN;
    private final double predictedMs;
    private final double predictedPerSecond;
    private final int draftN;
    private final int draftNAccepted;

    /**
     * Construct a Timings record with explicit field values. Use {@link #fromJson} to parse
     * the native {@code timings} block directly.
     *
     * @param cacheN             KV-cache hit count
     * @param promptN            prompt tokens processed
     * @param promptMs           prompt processing wall-clock milliseconds
     * @param promptPerSecond    prompt tokens per second
     * @param predictedN         tokens generated
     * @param predictedMs        generation wall-clock milliseconds
     * @param predictedPerSecond generated tokens per second
     * @param draftN             draft tokens generated by the speculative engine
     * @param draftNAccepted     draft tokens accepted by the target model
     */
    public Timings(
            int cacheN,
            long promptN,
            double promptMs,
            double promptPerSecond,
            long predictedN,
            double predictedMs,
            double predictedPerSecond,
            int draftN,
            int draftNAccepted) {
        this.cacheN = cacheN;
        this.promptN = promptN;
        this.promptMs = promptMs;
        this.promptPerSecond = promptPerSecond;
        this.predictedN = predictedN;
        this.predictedMs = predictedMs;
        this.predictedPerSecond = predictedPerSecond;
        this.draftN = draftN;
        this.draftNAccepted = draftNAccepted;
    }

    /**
     * Parse a {@link Timings} from a JSON object matching the native {@code timings} block.
     * Missing fields default to {@code 0}.
     *
     * @param node the {@code timings} object node; may be a missing-node
     * @return a populated {@link Timings} (all-zero when {@code node} is missing/null)
     */
    public static Timings fromJson(@Nullable JsonNode node) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return new Timings(0, 0, 0.0, 0.0, 0, 0.0, 0.0, 0, 0);
        }
        return new Timings(
                node.path("cache_n").asInt(0),
                node.path("prompt_n").asLong(0L),
                node.path("prompt_ms").asDouble(0.0),
                node.path("prompt_per_second").asDouble(0.0),
                node.path("predicted_n").asLong(0L),
                node.path("predicted_ms").asDouble(0.0),
                node.path("predicted_per_second").asDouble(0.0),
                node.path("draft_n").asInt(0),
                node.path("draft_n_accepted").asInt(0));
    }

    /**
     * KV-cache hit count for this completion.
     * @return number of tokens served from the KV cache without re-evaluation
     */
    public int getCacheN() {
        return cacheN;
    }

    /**
     * Prompt token count for this completion.
     * @return number of prompt tokens processed
     */
    public long getPromptN() {
        return promptN;
    }

    /**
     * Prompt processing wall-clock duration.
     * @return wall-clock milliseconds spent processing the prompt
     */
    public double getPromptMs() {
        return promptMs;
    }

    /**
     * Prompt throughput.
     * @return prompt tokens per second
     */
    public double getPromptPerSecond() {
        return promptPerSecond;
    }

    /**
     * Generated token count for this completion.
     * @return number of tokens generated
     */
    public long getPredictedN() {
        return predictedN;
    }

    /**
     * Generation wall-clock duration.
     * @return wall-clock milliseconds spent generating tokens
     */
    public double getPredictedMs() {
        return predictedMs;
    }

    /**
     * Generation throughput.
     * @return generated tokens per second
     */
    public double getPredictedPerSecond() {
        return predictedPerSecond;
    }

    /**
     * Draft-token count when speculative decoding is active.
     * @return number of draft tokens generated, or zero when speculative decoding was not active
     */
    public int getDraftN() {
        return draftN;
    }

    /**
     * Accepted draft-token count when speculative decoding is active.
     * @return number of draft tokens accepted by the target model, or zero when speculative decoding was not active
     */
    public int getDraftNAccepted() {
        return draftNAccepted;
    }
}
