// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.value;

import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Token-usage counters, modeled after the OpenAI / Llama Stack {@code usage} block.
 * <p>
 * Used by {@link ChatResponse}, {@link CompletionResult}, and {@link ServerMetrics}
 * to expose per-request and cumulative token counts.
 * </p>
 *
 * <p>Value equality / {@code toString} are generated by Lombok over the stored
 * counters. The derived {@link #getTotalTokens()} sum is included in {@code toString}
 * via {@link ToString.Include @ToString.Include} so the rendered output retains the
 * convenience field that the handwritten version exposed.</p>
 */
@ToString
@EqualsAndHashCode
public final class Usage {

    private final long promptTokens;
    private final long completionTokens;
    private final long cachedTokens;

    /**
     * Construct a usage record.
     *
     * @param promptTokens     number of prompt tokens
     * @param completionTokens number of completion tokens
     */
    public Usage(long promptTokens, long completionTokens) {
        this(promptTokens, completionTokens, 0L);
    }

    /**
     * Construct a usage record including the reused subset of prompt tokens.
     *
     * @param promptTokens logical prompt token count, including cached tokens
     * @param completionTokens number of completion tokens
     * @param cachedTokens prompt tokens served from KV cache without re-evaluation
     */
    public Usage(long promptTokens, long completionTokens, long cachedTokens) {
        this.promptTokens = promptTokens;
        this.completionTokens = completionTokens;
        this.cachedTokens = cachedTokens;
    }

    /**
     * Prompt-side token count.
     * @return number of prompt tokens
     */
    public long getPromptTokens() {
        return promptTokens;
    }

    /**
     * Completion-side token count.
     * @return number of completion tokens
     */
    public long getCompletionTokens() {
        return completionTokens;
    }

    /**
     * Prompt tokens reused from the KV cache.
     * @return cached subset of {@link #getPromptTokens()}
     */
    public long getCachedTokens() {
        return cachedTokens;
    }

    /**
     * Prompt tokens that required model evaluation.
     * @return prompt tokens minus the cached subset, clamped to zero for malformed upstream data
     */
    public long getProcessedPromptTokens() {
        return Math.max(0L, promptTokens - cachedTokens);
    }

    /**
     * Convenience sum of the prompt and completion counts.
     * @return sum of prompt and completion tokens
     */
    @ToString.Include
    public long getTotalTokens() {
        return promptTokens + completionTokens;
    }
}
