// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
// SPDX-FileCopyrightText: 2023-2025 Konstantin Herud
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.EqualsAndHashCode;
import net.ladenthin.llama.args.CliArg;
import org.jspecify.annotations.Nullable;

/**
 * Base class for CLI-style parameter builders.
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok over the parameters map.
 * {@code toString} is intentionally handwritten (not Lombok-generated): it emits the
 * accumulated parameters as a space-separated CLI argv-style string that callers can
 * forward to the native CLI. Replacing it with a Lombok field dump would break that
 * consumer contract.
 */
@EqualsAndHashCode
abstract class CliParameters {

    final Map<String, @Nullable String> parameters = new HashMap<>();

    /**
     * Store a scalar value (typically a primitive: int, long, float, double, boolean)
     * for the given key using {@link String#valueOf(Object)} and return this builder
     * typed as the concrete subtype so callers can collapse the
     * {@code parameters.put(...); return this;} pair into a single
     * {@code return putScalar(...);}.
     *
     * @param key   the parameter key
     * @param value the scalar value; autoboxed at the call site
     * @param <T>   the concrete subtype of this builder
     * @return this builder
     */
    // Self-typing builder idiom: caller fixes T to its concrete subtype so chained
    // calls return the concrete builder, not CliParameters.
    @SuppressWarnings({"unchecked", "TypeParameterUnusedInFormals"})
    protected final <T extends CliParameters> T putScalar(String key, Object value) {
        parameters.put(key, String.valueOf(value));
        return (T) this;
    }

    /**
     * Store the CLI-argument string of the given enum constant for the given key and
     * return this builder typed as the concrete subtype.
     *
     * @param key   the parameter key
     * @param value the enum constant; must implement {@link CliArg}
     * @param <T>   the concrete subtype of this builder
     * @return this builder
     */
    // Self-typing builder idiom — see putScalar above.
    @SuppressWarnings({"unchecked", "TypeParameterUnusedInFormals"})
    protected final <T extends CliParameters> T putEnum(String key, CliArg value) {
        parameters.put(key, value.getArgValue());
        return (T) this;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        for (Map.Entry<String, @Nullable String> entry : parameters.entrySet()) {
            builder.append(entry.getKey()).append(' ');
            String value = entry.getValue();
            if (value != null) {
                builder.append(value).append(' ');
            }
        }
        return builder.toString();
    }

    /**
     * Returns the accumulated parameters as a C-style {@code argv} array.
     *
     * <p>The first element is a placeholder for the program name, followed by alternating
     * argument keys and values (values are omitted for flag-style arguments).
     *
     * @return a fresh argv array suitable for passing to a native CLI parser
     */
    public String[] toArray() {
        // upper bound: 1 program-name slot + 2 entries (key, value) per parameter
        List<String> result = new ArrayList<>(1 + parameters.size() * 2);
        result.add(""); // c args contain the program name as the first argument, so we add an empty entry
        for (Map.Entry<String, @Nullable String> entry : parameters.entrySet()) {
            result.add(entry.getKey());
            String value = entry.getValue();
            if (value != null) {
                result.add(value);
            }
        }
        return result.toArray(new String[0]);
    }
}
