// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
// SPDX-FileCopyrightText: 2023-2025 Konstantin Herud
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import lombok.EqualsAndHashCode;
import net.ladenthin.llama.args.ContinuationMode;
import net.ladenthin.llama.args.MiroStat;
import net.ladenthin.llama.args.ReasoningFormat;
import net.ladenthin.llama.args.Sampler;
import org.jspecify.annotations.Nullable;

/**
 * Parameters used throughout inference of a {@link LlamaModel}, e.g., {@link LlamaModel#generate(InferenceParameters)}
 * and
 * {@link LlamaModel#complete(InferenceParameters)}.
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok with {@code callSuper=true}
 * so the parent {@link JsonParameters} parameters map participates in equality.
 * {@code toString} is inherited from {@link JsonParameters} and emits the accumulated
 * parameters as a JSON object string consumed by the native server.</p>
 */
@SuppressWarnings("unused")
@EqualsAndHashCode(callSuper = true)
public final class InferenceParameters extends JsonParameters {

    private static final String PARAM_PROMPT = "prompt";
    private static final String PARAM_INPUT_PREFIX = "input_prefix";
    private static final String PARAM_INPUT_SUFFIX = "input_suffix";
    private static final String PARAM_CACHE_PROMPT = "cache_prompt";
    private static final String PARAM_N_PREDICT = "n_predict";
    private static final String PARAM_TOP_K = "top_k";
    private static final String PARAM_TOP_P = "top_p";
    private static final String PARAM_MIN_P = "min_p";
    private static final String PARAM_TFS_Z = "tfs_z";
    private static final String PARAM_TYPICAL_P = "typical_p";
    private static final String PARAM_TEMPERATURE = "temperature";
    private static final String PARAM_DYNATEMP_RANGE = "dynatemp_range";
    private static final String PARAM_DYNATEMP_EXPONENT = "dynatemp_exponent";
    private static final String PARAM_REPEAT_LAST_N = "repeat_last_n";
    private static final String PARAM_REPEAT_PENALTY = "repeat_penalty";
    private static final String PARAM_FREQUENCY_PENALTY = "frequency_penalty";
    private static final String PARAM_PRESENCE_PENALTY = "presence_penalty";
    private static final String PARAM_MIROSTAT = "mirostat";
    private static final String PARAM_MIROSTAT_TAU = "mirostat_tau";
    private static final String PARAM_MIROSTAT_ETA = "mirostat_eta";
    private static final String PARAM_PENALIZE_NL = "penalize_nl";
    private static final String PARAM_N_KEEP = "n_keep";
    private static final String PARAM_SEED = "seed";
    private static final String PARAM_N_PROBS = "n_probs";
    private static final String PARAM_MIN_KEEP = "min_keep";
    private static final String PARAM_GRAMMAR = "grammar";
    private static final String PARAM_JSON_SCHEMA = "json_schema";
    private static final String PARAM_PENALTY_PROMPT = "penalty_prompt";
    private static final String PARAM_IGNORE_EOS = "ignore_eos";
    private static final String PARAM_LOGIT_BIAS = "logit_bias";
    private static final String PARAM_STOP = "stop";
    private static final String PARAM_SAMPLERS = "samplers";
    private static final String PARAM_STREAM = "stream";
    private static final String PARAM_USE_CHAT_TEMPLATE = "use_chat_template";
    private static final String PARAM_CHAT_TEMPLATE = "chat_template";
    private static final String PARAM_USE_JINJA = "use_jinja";
    private static final String PARAM_CHAT_TEMPLATE_KWARGS = "chat_template_kwargs";
    private static final String PARAM_MESSAGES = "messages";
    private static final String PARAM_TOP_N_SIGMA = "top_n_sigma";
    private static final String PARAM_REASONING_FORMAT = "reasoning_format";
    private static final String PARAM_REASONING_BUDGET_TOKENS = "reasoning_budget_tokens";
    private static final String PARAM_CONTINUE_FINAL_MESSAGE = "continue_final_message";

    /**
     * Creates inference parameters with the given prompt.
     *
     * @param prompt the prompt to start generation with
     */
    public InferenceParameters(String prompt) {
        // we always need a prompt
        setPrompt(prompt);
    }

    /**
     * Set the prompt to start generation with (default: empty)
     *
     * @param prompt the prompt to start generation with
     * @return this builder
     */
    public InferenceParameters setPrompt(String prompt) {
        parameters.put(PARAM_PROMPT, toJsonString(prompt));
        return this;
    }

    /**
     * Set a prefix for infilling (default: empty)
     *
     * @param inputPrefix the prefix for infilling
     * @return this builder
     */
    public InferenceParameters setInputPrefix(String inputPrefix) {
        parameters.put(PARAM_INPUT_PREFIX, toJsonString(inputPrefix));
        return this;
    }

    /**
     * Set a suffix for infilling (default: empty)
     *
     * @param inputSuffix the suffix for infilling
     * @return this builder
     */
    public InferenceParameters setInputSuffix(String inputSuffix) {
        parameters.put(PARAM_INPUT_SUFFIX, toJsonString(inputSuffix));
        return this;
    }

    /**
     * Whether to remember the prompt to avoid reprocessing it
     *
     * @param cachePrompt whether to cache the prompt
     * @return this builder
     */
    public InferenceParameters setCachePrompt(boolean cachePrompt) {
        return putScalar(PARAM_CACHE_PROMPT, cachePrompt);
    }

    /**
     * Set the number of tokens to predict (default: -1, -1 = infinity, -2 = until context filled)
     *
     * @param nPredict number of tokens to predict (-1 = infinity, -2 = until context filled)
     * @return this builder
     */
    public InferenceParameters setNPredict(int nPredict) {
        return putScalar(PARAM_N_PREDICT, nPredict);
    }

    /**
     * Set top-k sampling (default: 40, 0 = disabled)
     *
     * @param topK the top-k value (0 = disabled)
     * @return this builder
     */
    public InferenceParameters setTopK(int topK) {
        return putScalar(PARAM_TOP_K, topK);
    }

    /**
     * Set top-p sampling (default: 0.9, 1.0 = disabled)
     *
     * @param topP the top-p value (1.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setTopP(float topP) {
        return putScalar(PARAM_TOP_P, topP);
    }

    /**
     * Set min-p sampling (default: 0.1, 0.0 = disabled)
     *
     * @param minP the min-p value (0.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setMinP(float minP) {
        return putScalar(PARAM_MIN_P, minP);
    }

    /**
     * Set tail free sampling, parameter z (default: 1.0, 1.0 = disabled)
     *
     * @param tfsZ tail free sampling parameter z (1.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setTfsZ(float tfsZ) {
        return putScalar(PARAM_TFS_Z, tfsZ);
    }

    /**
     * Set locally typical sampling, parameter p (default: 1.0, 1.0 = disabled)
     *
     * @param typicalP the locally typical sampling parameter p (1.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setTypicalP(float typicalP) {
        return putScalar(PARAM_TYPICAL_P, typicalP);
    }

    /**
     * Set the temperature (default: 0.8)
     *
     * @param temperature the sampling temperature
     * @return this builder
     */
    public InferenceParameters setTemperature(float temperature) {
        return putScalar(PARAM_TEMPERATURE, temperature);
    }

    /**
     * Set the dynamic temperature range (default: 0.0, 0.0 = disabled)
     *
     * @param dynatempRange the dynamic temperature range (0.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setDynamicTemperatureRange(float dynatempRange) {
        return putScalar(PARAM_DYNATEMP_RANGE, dynatempRange);
    }

    /**
     * Set the dynamic temperature exponent (default: 1.0)
     *
     * @param dynatempExponent the dynamic temperature exponent
     * @return this builder
     */
    public InferenceParameters setDynamicTemperatureExponent(float dynatempExponent) {
        return putScalar(PARAM_DYNATEMP_EXPONENT, dynatempExponent);
    }

    /**
     * Set the last n tokens to consider for penalties (default: 64, 0 = disabled, -1 = ctx_size)
     *
     * @param repeatLastN the number of last tokens to consider for penalties (0 = disabled, -1 = ctx_size)
     * @return this builder
     */
    public InferenceParameters setRepeatLastN(int repeatLastN) {
        return putScalar(PARAM_REPEAT_LAST_N, repeatLastN);
    }

    /**
     * Set the penalty of repeated sequences of tokens (default: 1.0, 1.0 = disabled)
     *
     * @param repeatPenalty the repeat penalty (1.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setRepeatPenalty(float repeatPenalty) {
        return putScalar(PARAM_REPEAT_PENALTY, repeatPenalty);
    }

    /**
     * Set the repetition alpha frequency penalty (default: 0.0, 0.0 = disabled)
     *
     * @param frequencyPenalty the repetition alpha frequency penalty (0.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setFrequencyPenalty(float frequencyPenalty) {
        return putScalar(PARAM_FREQUENCY_PENALTY, frequencyPenalty);
    }

    /**
     * Set the repetition alpha presence penalty (default: 0.0, 0.0 = disabled)
     *
     * @param presencePenalty the repetition alpha presence penalty (0.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setPresencePenalty(float presencePenalty) {
        return putScalar(PARAM_PRESENCE_PENALTY, presencePenalty);
    }

    /**
     * Set MiroStat sampling strategies.
     *
     * @param mirostat the MiroStat sampling strategy
     * @return this builder
     */
    // .ordinal() is intentional here: the llama.cpp server expects the integer
    // ordinal of the MiroStat enum (0 = OFF, 1 = V1, 2 = V2) on the wire. The
    // declared order of MiroStat.values() matches the upstream contract.
    @SuppressWarnings("EnumOrdinal")
    public InferenceParameters setMiroStat(MiroStat mirostat) {
        return putScalar(PARAM_MIROSTAT, mirostat.ordinal());
    }

    /**
     * Set the MiroStat target entropy, parameter tau (default: 5.0)
     *
     * @param mirostatTau the MiroStat target entropy parameter tau
     * @return this builder
     */
    public InferenceParameters setMiroStatTau(float mirostatTau) {
        return putScalar(PARAM_MIROSTAT_TAU, mirostatTau);
    }

    /**
     * Set the MiroStat learning rate, parameter eta (default: 0.1)
     *
     * @param mirostatEta the MiroStat learning rate parameter eta
     * @return this builder
     */
    public InferenceParameters setMiroStatEta(float mirostatEta) {
        return putScalar(PARAM_MIROSTAT_ETA, mirostatEta);
    }

    /**
     * Whether to penalize newline tokens
     *
     * @param penalizeNl whether to penalize newline tokens
     * @return this builder
     */
    public InferenceParameters setPenalizeNl(boolean penalizeNl) {
        return putScalar(PARAM_PENALIZE_NL, penalizeNl);
    }

    /**
     * Set the number of tokens to keep from the initial prompt (default: 0, -1 = all)
     *
     * @param nKeep the number of tokens to keep from the initial prompt (-1 = all)
     * @return this builder
     */
    public InferenceParameters setNKeep(int nKeep) {
        return putScalar(PARAM_N_KEEP, nKeep);
    }

    /**
     * Set the RNG seed (default: -1, use random seed for &lt; 0)
     *
     * @param seed the RNG seed (use a negative value for a random seed)
     * @return this builder
     */
    public InferenceParameters setSeed(int seed) {
        return putScalar(PARAM_SEED, seed);
    }

    /**
     * Set the amount top tokens probabilities to output if greater than 0.
     *
     * @param nProbs the number of top token probabilities to output
     * @return this builder
     */
    public InferenceParameters setNProbs(int nProbs) {
        return putScalar(PARAM_N_PROBS, nProbs);
    }

    /**
     * Set the amount of tokens the samplers should return at least (0 = disabled)
     *
     * @param minKeep the minimum number of tokens samplers should return (0 = disabled)
     * @return this builder
     */
    public InferenceParameters setMinKeep(int minKeep) {
        return putScalar(PARAM_MIN_KEEP, minKeep);
    }

    /**
     * Set BNF-like grammar to constrain generations (see samples in grammars/ dir)
     *
     * @param grammar the BNF-like grammar string
     * @return this builder
     */
    public InferenceParameters setGrammar(String grammar) {
        parameters.put(PARAM_GRAMMAR, toJsonString(grammar));
        return this;
    }

    /**
     * Constrain generation to a JSON Schema for the duration of this request. The native
     * server converts the schema to a GBNF grammar internally; the schema string is passed
     * verbatim and must be valid JSON Schema.
     * <p>
     * Per-request equivalent of {@link ModelParameters#setJsonSchema(String)}, which is
     * applied once at model load time.
     *
     * @param schema JSON Schema as a JSON-encoded string (e.g. {@code "{\"type\":\"object\"...}"})
     * @return this builder
     */
    public InferenceParameters setJsonSchema(String schema) {
        parameters.put(PARAM_JSON_SCHEMA, schema);
        return this;
    }

    /**
     * Override which part of the prompt is penalized for repetition.
     * E.g. if original prompt is "Alice: Hello!" and penaltyPrompt is "Hello!", only the latter will be penalized if
     * repeated. See <a href="https://github.com/ggerganov/llama.cpp/pull/3727">pull request 3727</a> for more details.
     *
     * @param penaltyPrompt the string portion of the prompt to penalize for repetition
     * @return this builder
     */
    public InferenceParameters setPenaltyPrompt(String penaltyPrompt) {
        parameters.put(PARAM_PENALTY_PROMPT, toJsonString(penaltyPrompt));
        return this;
    }

    /**
     * Override which tokens to penalize for repetition.
     * E.g. if original prompt is "Alice: Hello!" and penaltyPrompt corresponds to the token ids of "Hello!", only the
     * latter will be penalized if repeated.
     * See <a href="https://github.com/ggerganov/llama.cpp/pull/3727">pull request 3727</a> for more details.
     *
     * @param tokens the token ids of the prompt portion to penalize for repetition
     * @return this builder
     */
    public InferenceParameters setPenaltyPrompt(int[] tokens) {
        if (tokens.length > 0) {
            parameters.put(
                    PARAM_PENALTY_PROMPT, serializer.buildIntArray(tokens).toString());
        }
        return this;
    }

    /**
     * Set whether to ignore end of stream token and continue generating (implies --logit-bias 2-inf)
     *
     * @param ignoreEos whether to ignore the end-of-stream token
     * @return this builder
     */
    public InferenceParameters setIgnoreEos(boolean ignoreEos) {
        return putScalar(PARAM_IGNORE_EOS, ignoreEos);
    }

    /**
     * Modify the likelihood of tokens appearing in the completion by their id. E.g., <code>Map.of(15043, 1f)</code>
     * to increase the  likelihood of token ' Hello', or a negative value to decrease it.
     * Note, this method overrides any previous calls to
     * <ul>
     *     <li>{@link #setTokenBias(Map)}</li>
     *     <li>{@link #disableTokens(Collection)}</li>
     *     <li>{@link #disableTokenIds(Collection)}}</li>
     * </ul>
     *
     * @param logitBias a map from token id to bias value
     * @return this builder
     */
    public InferenceParameters setTokenIdBias(Map<Integer, Float> logitBias) {
        if (!logitBias.isEmpty()) {
            parameters.put(
                    PARAM_LOGIT_BIAS,
                    serializer.buildTokenIdBiasArray(logitBias).toString());
        }
        return this;
    }

    /**
     * Set tokens to disable, this corresponds to {@link #setTokenIdBias(Map)} with a value of
     * {@link Float#NEGATIVE_INFINITY}.
     * Note, this method overrides any previous calls to
     * <ul>
     *     <li>{@link #setTokenIdBias(Map)}</li>
     *     <li>{@link #setTokenBias(Map)}</li>
     *     <li>{@link #disableTokens(Collection)}</li>
     * </ul>
     *
     * @param tokenIds the collection of token ids to disable
     * @return this builder
     */
    public InferenceParameters disableTokenIds(Collection<Integer> tokenIds) {
        if (!tokenIds.isEmpty()) {
            parameters.put(
                    PARAM_LOGIT_BIAS,
                    serializer.buildDisableTokenIdArray(tokenIds).toString());
        }
        return this;
    }

    /**
     * Modify the likelihood of tokens appearing in the completion by their id. E.g., <code>Map.of(" Hello", 1f)</code>
     * to increase the  likelihood of token id 15043, or a negative value to decrease it.
     * Note, this method overrides any previous calls to
     * <ul>
     *     <li>{@link #setTokenIdBias(Map)}</li>
     *     <li>{@link #disableTokens(Collection)}</li>
     *     <li>{@link #disableTokenIds(Collection)}}</li>
     * </ul>
     *
     * @param logitBias a map from token string to bias value
     * @return this builder
     */
    public InferenceParameters setTokenBias(Map<String, Float> logitBias) {
        if (!logitBias.isEmpty()) {
            parameters.put(
                    PARAM_LOGIT_BIAS,
                    serializer.buildTokenStringBiasArray(logitBias).toString());
        }
        return this;
    }

    /**
     * Set tokens to disable, this corresponds to {@link #setTokenBias(Map)} with a value of
     * {@link Float#NEGATIVE_INFINITY}.
     * Note, this method overrides any previous calls to
     * <ul>
     *     <li>{@link #setTokenBias(Map)}</li>
     *     <li>{@link #setTokenIdBias(Map)}</li>
     *     <li>{@link #disableTokenIds(Collection)}</li>
     * </ul>
     *
     * @param tokens the collection of token strings to disable
     * @return this builder
     */
    public InferenceParameters disableTokens(Collection<String> tokens) {
        if (!tokens.isEmpty()) {
            parameters.put(
                    PARAM_LOGIT_BIAS,
                    serializer.buildDisableTokenStringArray(tokens).toString());
        }
        return this;
    }

    /**
     * Set strings upon seeing which token generation is stopped
     *
     * @param stopStrings one or more strings that stop generation when encountered
     * @return this builder
     */
    public InferenceParameters setStopStrings(String... stopStrings) {
        if (stopStrings.length > 0) {
            parameters.put(PARAM_STOP, serializer.buildStopStrings(stopStrings).toString());
        }
        return this;
    }

    /**
     * Set which samplers to use for token generation in the given order
     *
     * @param samplers the samplers to use for token generation, in order
     * @return this builder
     */
    public InferenceParameters setSamplers(Sampler... samplers) {
        if (samplers.length > 0) {
            parameters.put(PARAM_SAMPLERS, serializer.buildSamplers(samplers).toString());
        }
        return this;
    }

    /**
     * Set whether generate should apply a chat template (default: false)
     *
     * @param useChatTemplate whether to apply a chat template
     * @return this builder
     */
    public InferenceParameters setUseChatTemplate(boolean useChatTemplate) {
        return putScalar(PARAM_USE_JINJA, useChatTemplate);
    }

    /**
     * Set the chat template string.
     *
     * @param chatTemplate the Jinja-style chat template to use
     * @return this builder
     */
    public InferenceParameters setChatTemplate(String chatTemplate) {
        parameters.put(PARAM_CHAT_TEMPLATE, toJsonString(chatTemplate));
        return this;
    }

    /**
     * Set custom Jinja template variables for this request. These are injected into
     * the chat template context during rendering. Values must be valid JSON.
     * <p>
     * Example:
     * <pre>{@code
     * Map<String, String> kwargs = new HashMap<>();
     * kwargs.put("enable_thinking", "true");
     * params.setChatTemplateKwargs(kwargs);
     * }</pre>
     *
     * @param kwargs map of variable names to JSON-serialized values
     * @return this builder
     */
    public InferenceParameters setChatTemplateKwargs(java.util.Map<String, String> kwargs) {
        parameters.put(
                PARAM_CHAT_TEMPLATE_KWARGS,
                serializer.buildRawValueObject(kwargs).toString());
        return this;
    }

    /**
     * Set the messages for chat-based inference.
     * - Allows <b>only one</b> system message.
     * - Allows <b>one or more</b> user/assistant messages.
     *
     * @param systemMessage an optional system message (may be null or empty)
     * @param messages a list of user/assistant message pairs (role as key, content as value)
     * @return this builder
     */
    public InferenceParameters setMessages(@Nullable String systemMessage, List<Pair<String, String>> messages) {
        parameters.put(
                PARAM_MESSAGES,
                serializer.buildMessages(systemMessage, messages).toString());
        return this;
    }

    /**
     * Multimodal-capable variant. Accepts {@link ChatMessage} objects so messages
     * with non-null {@link ChatMessage#getParts()} are serialized as OAI array-form
     * {@code content} (text + image_url parts). Plain text messages emit the legacy
     * string-form {@code content}, so this overload is also a drop-in replacement
     * for the {@code List<Pair>} variant when callers prefer the typed
     * {@link ChatMessage} surface.
     * <p>
     * Image parts require the model to have a multimodal projector loaded via
     * {@link ModelParameters#setMmproj(String)}. The upstream OAI chat parser
     * routes {@code image_url} blocks through the compiled-in {@code mtmd}
     * pipeline; no additional JNI configuration is needed on the Java side.
     * </p>
     *
     * @param messages ordered messages, including any {@code "system"} prelude
     * @return this builder
     */
    public InferenceParameters setMessages(List<ChatMessage> messages) {
        parameters.put(PARAM_MESSAGES, serializer.buildMessages(messages).toString());
        return this;
    }

    /**
     * Set the {@code messages} array directly from a pre-built JSON string. Use this
     * for the typed chat API (see {@link ChatRequest#buildMessagesJson()}) when the
     * conversation includes tool-call / tool-result turns that {@link #setMessages}
     * does not support.
     *
     * @param messagesJson the JSON array, e.g. {@code [{"role":"user","content":"hi"}]}
     * @return this builder
     */
    public InferenceParameters setMessagesJson(String messagesJson) {
        parameters.put(PARAM_MESSAGES, messagesJson);
        return this;
    }

    /**
     * Set the OAI-style {@code tools} array directly from a pre-built JSON string.
     * Pairs with {@link ChatRequest#buildToolsJson()} to enable tool calling.
     *
     * @param toolsJson the JSON array, e.g. {@code [{"type":"function","function":{...}}]}
     * @return this builder
     */
    public InferenceParameters setToolsJson(String toolsJson) {
        parameters.put("tools", toolsJson);
        return this;
    }

    /**
     * Set the OAI-style {@code tool_choice} hint.
     *
     * @param toolChoice the hint string (typically {@code "auto"}, {@code "none"}, or {@code "required"})
     * @return this builder
     */
    public InferenceParameters setToolChoice(String toolChoice) {
        parameters.put("tool_choice", toJsonString(toolChoice));
        return this;
    }

    /**
     * Set top-n-sigma sampling threshold (default: -1.0, disabled).
     * Only tokens whose logit is within {@code n} standard deviations of the maximum logit
     * are kept for sampling. Effective values are typically in the range 1.0–3.0.
     *
     * @param topNSigma the sigma threshold (-1.0 = disabled)
     * @return this builder
     */
    public InferenceParameters setTopNSigma(float topNSigma) {
        return putScalar(PARAM_TOP_N_SIGMA, topNSigma);
    }

    /**
     * Set how reasoning/thinking tokens emitted by models like DeepSeek-R1 and QwQ are
     * extracted and returned. Only effective when chat-template rendering is active
     * ({@link #setUseChatTemplate(boolean)}).
     *
     * @param reasoningFormat the format used to handle thinking tokens
     * @return this builder
     */
    public InferenceParameters setReasoningFormat(ReasoningFormat reasoningFormat) {
        parameters.put(PARAM_REASONING_FORMAT, toJsonString(reasoningFormat.getArgValue()));
        return this;
    }

    /**
     * Limit the number of reasoning tokens a thinking model (e.g. DeepSeek-R1, QwQ) may
     * emit before it is forced to stop reasoning and begin its response.
     * A value of {@code -1} (the default) disables the budget.
     *
     * @param budgetTokens maximum reasoning tokens (-1 = unlimited)
     * @return this builder
     */
    public InferenceParameters setReasoningBudgetTokens(int budgetTokens) {
        return putScalar(PARAM_REASONING_BUDGET_TOKENS, budgetTokens);
    }

    /**
     * Continue the final assistant message rather than starting a new one (vLLM/transformers compatible alias).
     * When {@code true}, {@code add_generation_prompt} is implicitly set to {@code false} and the last
     * assistant message in the conversation is extended without appending an end-of-turn token.
     * Mutually exclusive with {@code add_generation_prompt=true}.
     *
     * @param continueFinalMessage {@code true} to continue the last assistant message
     * @return this builder
     */
    public InferenceParameters setContinueFinalMessage(boolean continueFinalMessage) {
        return putScalar(PARAM_CONTINUE_FINAL_MESSAGE, continueFinalMessage);
    }

    /**
     * Continue the final assistant message and pin the continuation to a specific channel.
     * Selects the reasoning or content portion of the last assistant message to extend from,
     * matching llama.cpp's string-valued {@code continue_final_message}
     * ({@code "reasoning_content"} or {@code "content"}). Mutually exclusive with
     * {@code add_generation_prompt=true}.
     *
     * @param mode the channel to continue from
     * @return this builder
     */
    public InferenceParameters setContinueFinalMessage(ContinuationMode mode) {
        parameters.put(PARAM_CONTINUE_FINAL_MESSAGE, toJsonString(mode.getValue()));
        return this;
    }

    InferenceParameters setStream(boolean stream) {
        return putScalar(PARAM_STREAM, stream);
    }
}
