// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama;

import java.util.List;
import java.util.function.Consumer;
import lombok.ToString;
import org.jspecify.annotations.Nullable;

/**
 * Thin multi-turn conversation wrapper over a {@link LlamaModel} slot. Maintains an
 * accumulating list of {@link ChatMessage} turns and forwards each {@link #send(String)}
 * to the underlying chat-completion API with the full transcript so far. KV-cache state
 * for the bound slot can be persisted via {@link #save(String)} and restored with
 * {@link #restore(String)}, which delegate to {@link LlamaModel#saveSlot(int, String)}
 * and {@link LlamaModel#restoreSlot(int, String)}.
 * <p>
 * Thread-safety: all public methods are serialized on a private intrinsic lock, so
 * concurrent {@link #send(String)} calls from multiple threads produce a well-formed
 * transcript with strict user/assistant alternation. {@link #stream(String)} sets a
 * "streaming in progress" flag and returns the iterator without holding the lock;
 * while that flag is set, {@link #send(String)}, a second {@link #stream(String)},
 * {@link #save(String)}, and {@link #restore(String)} fail-fast with
 * {@link IllegalStateException} until the caller invokes
 * {@link #commitStreamedReply(String)}.
 * </p>
 *
 * <p>{@code toString} is generated by Lombok over the slot id, system message, and
 * accumulated turns. The owning {@link LlamaModel} is excluded because its
 * {@code toString} would render native state. The {@code paramsCustomizer}
 * {@link Consumer} is excluded because lambda {@code toString} is the implementation
 * hash, not useful in logs. The intrinsic {@code lock} is excluded as a noise field.
 * {@code equals}/{@code hashCode} are intentionally NOT generated: a session is a
 * mutable lifecycle handle managed by identity.</p>
 */
@ToString
public final class Session implements AutoCloseable {

    // Owning model — its toString would recursively render native state.
    @ToString.Exclude
    private final LlamaModel model;

    private final int slotId;

    /**
     * Append-only transcript with two-phase commit semantics. See the
     * {@link ChatTranscript} class Javadoc for the full invariant statement
     * and the {@code ChatTranscriptTest} class for the running-documentation
     * tests that pin the contract.
     */
    private final ChatTranscript transcript;

    // Lambda Consumer — toString is the implementation hash, not useful in logs.
    @ToString.Exclude
    private final @Nullable Consumer<InferenceParameters> paramsCustomizer;

    // Intrinsic lock used only for synchronisation; rendering its identity adds noise.
    @ToString.Exclude
    private final Object lock = new Object();

    private boolean streamingActive;

    /**
     * Create a session bound to a specific slot id, with an optional system prompt
     * applied to every {@link #send(String)} call.
     *
     * @param model the underlying model
     * @param slotId the slot id used by {@link #save(String)} / {@link #restore(String)}
     * @param systemMessage optional system prompt (may be {@code null} or empty)
     */
    public Session(LlamaModel model, int slotId, @Nullable String systemMessage) {
        this(model, slotId, systemMessage, null);
    }

    /**
     * Create a session with a customizer that gets to mutate the
     * {@link InferenceParameters} for every call (e.g. set temperature, n_predict).
     *
     * @param model the underlying model
     * @param slotId the slot id
     * @param systemMessage optional system prompt
     * @param paramsCustomizer applied to each request's parameters; may be {@code null}
     */
    public Session(
            LlamaModel model,
            int slotId,
            @Nullable String systemMessage,
            @Nullable Consumer<InferenceParameters> paramsCustomizer) {
        this.model = model;
        this.slotId = slotId;
        this.transcript = new ChatTranscript(systemMessage);
        this.paramsCustomizer = paramsCustomizer;
    }

    /**
     * Send a user message and return the assistant's text reply, appending both to the transcript.
     *
     * @param userMessage the user turn to append before invoking the model
     * @return the assistant's reply text
     */
    public String send(String userMessage) {
        synchronized (lock) {
            if (streamingActive) {
                throw new IllegalStateException(
                        "stream in progress on slot " + slotId
                                + " (transcript=" + transcript.size() + " turns)"
                                + "; call commitStreamedReply(...) before send(...)");
            }
            // Two-phase commit: build the wire-format with the pending user turn
            // outside the transcript via messagesWithPendingUserTurn(...). On
            // model success, commit BOTH turns atomically through appendRound(...).
            // On model failure, nothing was committed — no rollback logic needed.
            // Invariant pinned by ChatTranscriptTest.
            InferenceParameters params = buildParamsWithPendingUserTurn(userMessage);
            String reply = model.chatCompleteText(params);
            transcript.appendRound(userMessage, reply);
            return reply;
        }
    }

    /**
     * Streaming variant of {@link #send(String)}. The returned iterable yields chunks of
     * the assistant reply; consume it fully (or via try-with-resources) before calling
     * {@link #send(String)} again, because the assistant turn is only appended to the
     * transcript when the caller invokes {@link #commitStreamedReply(String)}.
     *
     * @param userMessage the user turn to append before starting the stream
     * @return a {@link LlamaIterable} that yields assistant reply chunks
     */
    public LlamaIterable stream(String userMessage) {
        synchronized (lock) {
            if (streamingActive) {
                throw new IllegalStateException(
                        "stream in progress on slot " + slotId
                                + " (transcript=" + transcript.size() + " turns)"
                                + "; call commitStreamedReply(...) before stream(...)");
            }
            // Two-phase commit: see send(). The user turn is committed only after
            // generateChat successfully returns the iterable; the assistant turn is
            // committed separately by commitStreamedReply(...).
            LlamaIterable iterable = model.generateChat(buildParamsWithPendingUserTurn(userMessage));
            transcript.appendUserTurn(userMessage);
            streamingActive = true;
            return iterable;
        }
    }

    /**
     * Record an assistant reply that was produced by a previous {@link #stream(String)}
     * call. Called by the caller after it has accumulated the streamed text.
     *
     * @param assistantText the assistant text accumulated from a prior {@link #stream(String)} call
     */
    public void commitStreamedReply(String assistantText) {
        synchronized (lock) {
            if (!streamingActive) {
                throw new IllegalStateException(
                        "no stream in progress on slot " + slotId
                                + " (transcript=" + transcript.size() + " turns)"
                                + "; call stream(...) first");
            }
            transcript.appendAssistantTurn(assistantText);
            streamingActive = false;
        }
    }

    /**
     * Save this session's slot KV cache to {@code filepath}.
     *
     * @param filepath destination file path passed to {@link LlamaModel#saveSlot(int, String)}
     * @return the JSON response from the native save action
     */
    public String save(String filepath) {
        synchronized (lock) {
            if (streamingActive) {
                throw new IllegalStateException(
                        "stream in progress on slot " + slotId
                                + " (transcript=" + transcript.size() + " turns)"
                                + "; call commitStreamedReply(...) before save(...)");
            }
            return model.saveSlot(slotId, filepath);
        }
    }

    /**
     * Restore this session's slot KV cache from {@code filepath}.
     *
     * @param filepath source file path passed to {@link LlamaModel#restoreSlot(int, String)}
     * @return the JSON response from the native restore action
     */
    public String restore(String filepath) {
        synchronized (lock) {
            if (streamingActive) {
                throw new IllegalStateException(
                        "stream in progress on slot " + slotId
                                + " (transcript=" + transcript.size() + " turns)"
                                + "; call commitStreamedReply(...) before restore(...)");
            }
            return model.restoreSlot(slotId, filepath);
        }
    }

    /**
     * Transcript accessor.
     * @return the accumulated transcript so far, in order, including the system message if any
     */
    public List<ChatMessage> getMessages() {
        synchronized (lock) {
            return transcript.snapshot();
        }
    }

    /** Erase the bound slot's KV cache. Does not modify the in-memory transcript. */
    @Override
    public void close() {
        synchronized (lock) {
            model.eraseSlot(slotId);
        }
    }

    /**
     * Build inference parameters with a pending user turn appended to the existing
     * transcript — without mutating the underlying {@link ChatTranscript}. The
     * actual transcript mutation happens AFTER the model call returns successfully,
     * either via {@link ChatTranscript#appendRound(String, String)} (send path)
     * or {@link ChatTranscript#appendUserTurn(String)} (stream path).
     *
     * @param pendingUserMessage the user turn to include in the wire format
     * @return inference parameters carrying transcript + pending user turn
     */
    private InferenceParameters buildParamsWithPendingUserTurn(String pendingUserMessage) {
        InferenceParameters params = new InferenceParameters("")
                .setMessages(
                        transcript.getSystemMessage(),
                        transcript.messagesWithPendingUserTurn(pendingUserMessage));
        if (paramsCustomizer != null) {
            paramsCustomizer.accept(params);
        }
        return params;
    }
}
