// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama;

import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Token-usage counters, modeled after the OpenAI / Llama Stack {@code usage} block.
 * <p>
 * Used by {@link ServerMetrics} to expose cumulative server-wide token totals and
 * (in a future {@code ChatResponse}) per-completion counts.
 * </p>
 *
 * <p>Value equality / {@code toString} are generated by Lombok over the two stored
 * counters. The derived {@link #getTotalTokens()} sum is included in {@code toString}
 * via {@link ToString.Include @ToString.Include} so the rendered output retains the
 * convenience field that the handwritten version exposed.</p>
 */
@ToString
@EqualsAndHashCode
public final class Usage {

    private final long promptTokens;
    private final long completionTokens;

    /**
     * Construct a usage record.
     *
     * @param promptTokens     number of prompt tokens
     * @param completionTokens number of completion tokens
     */
    public Usage(long promptTokens, long completionTokens) {
        this.promptTokens = promptTokens;
        this.completionTokens = completionTokens;
    }

    /**
     * Prompt-side token count.
     * @return number of prompt tokens
     */
    public long getPromptTokens() {
        return promptTokens;
    }

    /**
     * Completion-side token count.
     * @return number of completion tokens
     */
    public long getCompletionTokens() {
        return completionTokens;
    }

    /**
     * Convenience sum of the prompt and completion counts.
     * @return sum of prompt and completion tokens
     */
    @ToString.Include
    public long getTotalTokens() {
        return promptTokens + completionTokens;
    }
}
