// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.value;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalLong;
import lombok.EqualsAndHashCode;

/**
 * Metadata read from a GGUF file's header and key/value table by
 * {@link net.ladenthin.llama.GgufInspector} — <b>without loading the model</b> (no native
 * library, no tensor data, no RAM commitment). Complements {@link ModelMeta}, which describes an
 * already-<em>loaded</em> model via the native layer.
 *
 * <p>The full key/value table is exposed via {@link #getEntries()} (GGUF keys such as
 * {@code general.architecture} mapped to their decoded values), with typed convenience accessors
 * for the fields a model picker typically needs. Integer-typed GGUF values (u8…u64/i8…i64) decode
 * to {@link Long}, floats to {@link Double}, booleans to {@link Boolean}, strings to
 * {@link String}, and arrays to unmodifiable {@code List<Object>}.</p>
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok over all fields. {@code toString}
 * is intentionally handwritten (not Lombok-generated): the entry table can hold six-figure
 * token arrays, so it renders a compact one-line summary instead of dumping the map.</p>
 */
@EqualsAndHashCode
public final class GgufMetadata {

    /** GGUF key holding the model architecture (e.g. {@code "llama"}, {@code "qwen3"}). */
    public static final String KEY_ARCHITECTURE = "general.architecture";

    /** GGUF key holding the human-readable model name. */
    public static final String KEY_NAME = "general.name";

    /** GGUF key holding the total parameter count. */
    public static final String KEY_PARAMETER_COUNT = "general.parameter_count";

    /** GGUF key holding the numeric {@code llama_ftype} quantization id. */
    public static final String KEY_FILE_TYPE = "general.file_type";

    /** GGUF key holding the Jinja chat template. */
    public static final String KEY_CHAT_TEMPLATE = "tokenizer.chat_template";

    /**
     * Suffix of the per-architecture context-length key
     * ({@code "<architecture>.context_length"}).
     */
    public static final String KEY_SUFFIX_CONTEXT_LENGTH = ".context_length";

    private final int version;
    private final long tensorCount;
    private final Map<String, Object> entries;

    /**
     * Construct a metadata snapshot.
     *
     * @param version     the GGUF container version (2 or 3)
     * @param tensorCount the number of tensors declared in the header
     * @param entries     the decoded key/value table, in file order
     */
    public GgufMetadata(int version, long tensorCount, Map<String, Object> entries) {
        this.version = version;
        this.tensorCount = tensorCount;
        this.entries = Collections.unmodifiableMap(new LinkedHashMap<String, Object>(entries));
    }

    /**
     * GGUF container version accessor.
     * @return the container version (2 or 3)
     */
    public int getVersion() {
        return version;
    }

    /**
     * Tensor count accessor.
     * @return the number of tensors declared in the header
     */
    public long getTensorCount() {
        return tensorCount;
    }

    /**
     * Full key/value table accessor.
     * @return an unmodifiable view of the decoded key/value table, in file order
     */
    public Map<String, Object> getEntries() {
        return entries;
    }

    /**
     * Raw value lookup.
     *
     * @param key the GGUF key
     * @return the decoded value, or {@link Optional#empty()} when the key is absent
     */
    public Optional<Object> getValue(String key) {
        return Optional.ofNullable(entries.get(key));
    }

    /**
     * String value lookup.
     *
     * @param key the GGUF key
     * @return the string value, or {@link Optional#empty()} when absent or not a string
     */
    public Optional<String> getString(String key) {
        Object value = entries.get(key);
        return value instanceof String ? Optional.of((String) value) : Optional.<String>empty();
    }

    /**
     * Integer value lookup (any numeric GGUF type, widened to {@code long}).
     *
     * @param key the GGUF key
     * @return the numeric value, or {@link OptionalLong#empty()} when absent or not numeric
     */
    public OptionalLong getLong(String key) {
        Object value = entries.get(key);
        return value instanceof Number ? OptionalLong.of(((Number) value).longValue()) : OptionalLong.empty();
    }

    /**
     * Model architecture accessor ({@value #KEY_ARCHITECTURE}).
     * @return the architecture (e.g. {@code "llama"}), or {@link Optional#empty()} when absent
     */
    public Optional<String> getArchitecture() {
        return getString(KEY_ARCHITECTURE);
    }

    /**
     * Model name accessor ({@value #KEY_NAME}).
     * @return the human-readable model name, or {@link Optional#empty()} when absent
     */
    public Optional<String> getModelName() {
        return getString(KEY_NAME);
    }

    /**
     * Parameter count accessor ({@value #KEY_PARAMETER_COUNT}).
     * @return the total parameter count, or {@link OptionalLong#empty()} when absent
     */
    public OptionalLong getParameterCount() {
        return getLong(KEY_PARAMETER_COUNT);
    }

    /**
     * Quantization id accessor ({@value #KEY_FILE_TYPE}): the numeric {@code llama_ftype}
     * (matches the values behind {@link net.ladenthin.llama.args.QuantizationType}).
     * @return the {@code llama_ftype} id, or {@link OptionalLong#empty()} when absent
     */
    public OptionalLong getFileType() {
        return getLong(KEY_FILE_TYPE);
    }

    /**
     * Chat template accessor ({@value #KEY_CHAT_TEMPLATE}).
     * @return the Jinja chat template, or {@link Optional#empty()} when absent
     */
    public Optional<String> getChatTemplate() {
        return getString(KEY_CHAT_TEMPLATE);
    }

    /**
     * Trained context length accessor: reads {@code "<architecture>.context_length"}, so it
     * requires {@link #getArchitecture()} to be present.
     * @return the trained context length, or {@link OptionalLong#empty()} when the
     *     architecture or the length key is absent
     */
    public OptionalLong getContextLength() {
        Optional<String> architecture = getArchitecture();
        if (!architecture.isPresent()) {
            return OptionalLong.empty();
        }
        return getLong(architecture.get() + KEY_SUFFIX_CONTEXT_LENGTH);
    }

    @Override
    public String toString() {
        return "GGUF v" + version + " (" + tensorCount + " tensors, " + entries.size() + " keys, arch="
                + getArchitecture().orElse("?") + ")";
    }
}
