// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.value;

import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * A LoRA adapter registered on the loaded model, as reported by the native
 * {@code GET /lora-adapters}-equivalent task (see
 * {@code net.ladenthin.llama.LlamaModel#getLoraAdapters()}).
 * <p>
 * Adapters are loaded at model-load time via
 * {@link net.ladenthin.llama.parameters.ModelParameters#addLoraAdapter(String)} /
 * {@link net.ladenthin.llama.parameters.ModelParameters#addLoraScaledAdapter(String, float)}; their
 * {@linkplain #getScale() scale} can then be changed at runtime without reloading the model via
 * {@code net.ladenthin.llama.LlamaModel#setLoraAdapters(java.util.Map)}. A scale of {@code 0}
 * disables the adapter.
 * </p>
 *
 * <p>{@code toString} and {@code equals}/{@code hashCode} are generated by Lombok over all
 * fields.</p>
 */
@ToString
@EqualsAndHashCode
public final class LoraAdapter {

    private final int id;
    private final String path;
    private final float scale;
    private final String taskName;
    private final String promptPrefix;

    /**
     * Construct a LoRA adapter view.
     *
     * @param id           the adapter id (its position in the load-time adapter list)
     * @param path         the GGUF file path the adapter was loaded from
     * @param scale        the currently applied scale; {@code 0} means disabled
     * @param taskName     the adapter's task name from its GGUF metadata; may be empty
     * @param promptPrefix the adapter's prompt prefix from its GGUF metadata; may be empty
     */
    public LoraAdapter(int id, String path, float scale, String taskName, String promptPrefix) {
        this.id = id;
        this.path = path;
        this.scale = scale;
        this.taskName = taskName;
        this.promptPrefix = promptPrefix;
    }

    /**
     * Adapter id used to address this adapter in scale updates.
     *
     * @return the adapter id (its position in the load-time adapter list)
     */
    public int getId() {
        return id;
    }

    /**
     * File path of the adapter.
     *
     * @return the GGUF file path the adapter was loaded from
     */
    public String getPath() {
        return path;
    }

    /**
     * Currently applied adapter scale.
     *
     * @return the scale; {@code 0} means the adapter is disabled
     */
    public float getScale() {
        return scale;
    }

    /**
     * Task name declared in the adapter's GGUF metadata.
     *
     * @return the task name, or an empty string when the adapter declares none
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * Prompt prefix declared in the adapter's GGUF metadata.
     *
     * @return the prompt prefix, or an empty string when the adapter declares none
     */
    public String getPromptPrefix() {
        return promptPrefix;
    }
}
