// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.value;

import lombok.EqualsAndHashCode;

/**
 * One model entry from the router-mode model registry (the upstream {@code GET /models}
 * response served by {@link net.ladenthin.llama.server.NativeServer} when started with
 * {@code --models-dir}). Carries the model identifier, its lifecycle {@link Status}, the raw
 * status string as emitted by the server, and the failure marker the router attaches when a
 * worker exited abnormally.
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok over all fields.
 * {@code toString} is intentionally handwritten (not Lombok-generated) so that router traces
 * in logs render as "{@code id [status]}" or "{@code id [status, failed exit=N]}" instead of
 * a verbose field dump.</p>
 */
@EqualsAndHashCode
public final class RouterModel {

    /**
     * Router-side model lifecycle state. Mirrors the upstream {@code server_model_status}
     * enum (serialized by {@code server_model_status_to_string} in {@code server-models.h}).
     */
    public enum Status {
        /** The model file is being downloaded. */
        DOWNLOADING,
        /** The model file is downloaded but no worker has been started. */
        DOWNLOADED,
        /** No worker is running for this model. */
        UNLOADED,
        /** A worker is starting / loading the model. */
        LOADING,
        /** The worker is up and serving requests. */
        LOADED,
        /** The worker is sleeping (idle-unloaded, resumable). */
        SLEEPING,
        /** Any status string this binding does not recognize. */
        UNKNOWN;

        /**
         * Map the upstream status string (e.g. {@code "loaded"}) to the enum. Matching is
         * exact: upstream emits exactly these lowercase strings
         * ({@code server_model_status_to_string}), so no case folding is applied (which
         * would also trip findsecbugs' IMPROPER_UNICODE on transformation-based matching).
         *
         * @param value the raw {@code status.value} string; may be {@code null}
         * @return the matching status, or {@link #UNKNOWN} for {@code null}/unrecognized values
         */
        public static Status fromValue(String value) {
            if (value == null) {
                return UNKNOWN;
            }
            switch (value) {
                case "downloading":
                    return DOWNLOADING;
                case "downloaded":
                    return DOWNLOADED;
                case "unloaded":
                    return UNLOADED;
                case "loading":
                    return LOADING;
                case "loaded":
                    return LOADED;
                case "sleeping":
                    return SLEEPING;
                default:
                    return UNKNOWN;
            }
        }
    }

    private final String id;
    private final Status status;
    private final String statusValue;
    private final boolean failed;
    private final int exitCode;

    /**
     * Construct a router model entry.
     *
     * @param id          the model identifier used in {@code /models/load} and per-request
     *                    {@code "model"} selection
     * @param status      the parsed lifecycle status
     * @param statusValue the raw {@code status.value} string as emitted by the server (kept so
     *                    an {@link Status#UNKNOWN} mapping still exposes what the server said)
     * @param failed      whether the router flagged the model's worker as failed
     *                    ({@code status.failed} in the wire format)
     * @param exitCode    the failed worker's exit code ({@code status.exit_code}); {@code 0}
     *                    when not failed
     */
    public RouterModel(String id, Status status, String statusValue, boolean failed, int exitCode) {
        this.id = id;
        this.status = status;
        this.statusValue = statusValue;
        this.failed = failed;
        this.exitCode = exitCode;
    }

    /**
     * Model identifier accessor.
     * @return the model identifier
     */
    public String getId() {
        return id;
    }

    /**
     * Lifecycle status accessor.
     * @return the parsed lifecycle status
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Raw status string accessor.
     * @return the raw {@code status.value} string as emitted by the server
     */
    public String getStatusValue() {
        return statusValue;
    }

    /**
     * Failure marker accessor.
     * @return {@code true} when the router flagged the model's worker as failed
     */
    public boolean isFailed() {
        return failed;
    }

    /**
     * Failed worker exit code accessor.
     * @return the worker's exit code; {@code 0} when not failed
     */
    public int getExitCode() {
        return exitCode;
    }

    @Override
    public String toString() {
        if (failed) {
            return id + " [" + statusValue + ", failed exit=" + exitCode + "]";
        }
        return id + " [" + statusValue + "]";
    }
}
