// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.value;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import lombok.EqualsAndHashCode;

/**
 * A point-in-time snapshot of a {@link net.ladenthin.llama.Session}: the file that holds the
 * slot's saved KV-cache state (written by the native slot-save action) paired with the
 * transcript turns committed at checkpoint time. Produced by
 * {@link net.ladenthin.llama.Session#checkpoint(String)} and consumed by
 * {@link net.ladenthin.llama.Session#rewind(SessionCheckpoint)} — the KV file restores the
 * native state, the turn list restores the matching in-memory transcript, so the two can
 * never drift apart.
 *
 * <p>The checkpoint file's lifecycle is <b>caller-managed</b> (same philosophy as
 * {@code Session.save(filepath)}): delete it when no checkpoint referencing it is needed
 * anymore. KV dumps grow with context usage and can reach hundreds of MB for long
 * conversations.</p>
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok over all fields.
 * {@code toString} is intentionally handwritten (not Lombok-generated) so a checkpoint
 * renders compactly as "{@code filepath (N turns)}" instead of dumping the transcript.</p>
 */
@EqualsAndHashCode
public final class SessionCheckpoint {

    private final String filepath;
    private final List<Pair<String, String>> turns;

    /**
     * Construct a checkpoint.
     *
     * @param filepath the file the slot KV state was saved to
     * @param turns    the transcript turns committed at checkpoint time, in order (copied)
     */
    public SessionCheckpoint(String filepath, List<Pair<String, String>> turns) {
        this.filepath = filepath;
        this.turns = Collections.unmodifiableList(new ArrayList<Pair<String, String>>(turns));
    }

    /**
     * Checkpoint file accessor.
     * @return the file holding the saved slot KV state
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * Transcript snapshot accessor.
     * @return an unmodifiable view of the (role, text) turns committed at checkpoint time
     */
    public List<Pair<String, String>> getTurns() {
        return turns;
    }

    @Override
    public String toString() {
        return filepath + " (" + turns.size() + " turns)";
    }
}
